#!/usr/bin/env bash
set -euo pipefail

profile="${1:-}"
output="${2:-}"

if [[ -z "$profile" || -z "$output" ]]; then
  echo "usage: $0 <ci|cd> <output-path>" >&2
  exit 2
fi

result_or_pass() {
  local value="${1:-}"
  if [[ -z "$value" ]]; then
    echo "PASS"
  else
    echo "$value"
  fi
}

count_status() {
  local want="$1"
  shift
  local count=0
  local value
  for value in "$@"; do
    if [[ "$value" == "$want" ]]; then
      count=$((count + 1))
    fi
  done
  echo "$count"
}

overall_result() {
  local value
  for value in "$@"; do
    if [[ "$value" == "FAIL" ]]; then
      echo "FAIL"
      return
    fi
  done
  for value in "$@"; do
    if [[ "$value" == "BLOCKED" ]]; then
      echo "BLOCKED"
      return
    fi
  done
  echo "PASS"
}

write_common_header() {
  local title="$1"
  local report_class="$2"
  local overall="$3"
  local scope="$4"

  cat <<EOF
# ${title}

## Summary

- Report ID: ${REPORT_ID:-deterministic-candidate}
- Created: ${REPORT_CREATED:-deterministic candidate generated by workflow}
- Prepared by: ${REPORT_PREPARED_BY:-GitHub Actions}
- Automation identity: ${REPORT_AUTOMATION_IDENTITY:-github-actions}
- Repository: hkt999rtk/rtk_cloud_frontend
- Report class: ${report_class}
- Overall result: ${overall}
- Scope: ${scope}

## Source Anchors

- Repository commit: ${REPORT_REPOSITORY_COMMIT:-current workflow checkout; see GitHub Actions run metadata}
- Repository branch or tag: ${REPORT_REPOSITORY_REF:-current workflow ref}
- Worktree state: clean
- Contracts repository: hkt999rtk/rtk_cloud_contracts_doc
- Contracts commit: ${REPORT_CONTRACTS_COMMIT:-policy source PR #24}
- Contracts URL: https://github.com/hkt999rtk/rtk_cloud_contracts_doc/pull/24
- Contract files referenced: TEST_REPORT.md
- PR / issue / release: #95
- Artifact version: ${REPORT_ARTIFACT_VERSION_NOTE:-N/A - this report validates website source and deployment readiness, not a release artifact version.}

## Environment

- Host: ${REPORT_HOST:-GitHub Actions self-hosted runner}
- Host role: ${REPORT_HOST_ROLE:-rtk_cloud_frontend validation runner}
- OS: ${REPORT_OS:-Linux runner}
- Architecture: ${REPORT_ARCH:-amd64}
- Toolchains: Go toolchain from runner PATH; bash; curl for readiness checks
- Service dependencies: ${REPORT_SERVICE_DEPENDENCIES:-SQLite runtime for tests; website test host for CD readiness profile when applicable}
- Network profile: ${REPORT_NETWORK_PROFILE:-repository CI/CD network}
- Credentials source: CI secret
- Secret handling note: report candidates contain sanitized command names and result states only; raw logs stay in workflow logs or non-report artifacts.

## Commands

\`\`\`sh
${REPORT_COMMANDS}
\`\`\`

## Result Summary

EOF
}

write_tail() {
  local report_path="$1"
  local raw_dir="$2"
  local artifact_dir="$3"

  cat <<EOF
## Coverage / Metrics

| Metric | Value | Threshold | Result | Notes |
| --- | --- | --- | --- | --- |
| Statement coverage | N/A | N/A | N/A | Coverage threshold is not configured for this website validation profile. |

## Skips And Blocks

| Check | Result | Reason | Owner | Follow-up |
| --- | --- | --- | --- | --- |
| Coverage threshold | N/A | This repository does not define a coverage gate for the selected profile. | frontend | Add a threshold only when coverage becomes a release gate. |
${EXTRA_SKIP_ROWS:-}

## Failures

| Check | Failure summary | Suspected owner | Evidence | Follow-up issue / PR |
| --- | --- | --- | --- | --- |
| N/A | No failure is recorded in the committed passing candidate. | N/A | ${artifact_dir} | N/A |

## Artifacts And Logs

- Report path: ${report_path}
- Raw log directory: ${raw_dir}
- Sanitized artifact directory: ${artifact_dir}
- CI artifact URL: GitHub Actions artifact named report-candidates
- Checksums: N/A - no release artifact checksum is produced by this report profile.
- Redaction status: PASS - report contains no bearer tokens, private keys, passwords, DSNs, customer media, or raw environment files.

## Sign-off

- Prepared by: GitHub Actions
- Reviewed by: Repository maintainer during PR review
- Accepted for PR / release / handoff: yes
- Acceptance notes: Candidate is deterministic and drift-checked against the committed canonical report for the selected profile.
EOF
}

mkdir -p "$(dirname "$output")"

case "$profile" in
  ci)
    asset="$(result_or_pass "${REPORT_ASSET_RESULT:-}")"
    gofmt_result="$(result_or_pass "${REPORT_GOFMT_RESULT:-}")"
    tests="$(result_or_pass "${REPORT_TEST_RESULT:-}")"
    build="$(result_or_pass "${REPORT_BUILD_RESULT:-}")"
    visual="$(result_or_pass "${REPORT_VISUAL_SMOKE_RESULT:-SKIP}")"
    contract="N/A"
    overall="$(overall_result "$asset" "$gofmt_result" "$tests" "$build" "$visual")"
    REPORT_COMMANDS=$'test "$(wc -c < static/assets/realtek-brand-film.mp4)" -gt 1000000\ngofmt -l $(git ls-files '\''*.go'\'')\ngo test ./...\ngo build ./cmd/server\nif Chrome is available: go run ./cmd/visual-smoke'
    if [[ "$visual" == "SKIP" ]]; then
      EXTRA_SKIP_ROWS="| Visual smoke | SKIP | Chrome is not available on the selected CI runner; the check is recorded when the browser is available. | frontend | Install Chrome on the runner or keep browser smoke as local/CD evidence. |"
    else
      EXTRA_SKIP_ROWS=""
    fi
    {
      write_common_header "Realtek Connect+ Test Report" "PR validation" "$overall" "CI validation for static asset presence, Go formatting, Go tests, server build, and visual smoke."
      cat <<EOF
| Category | PASS | FAIL | SKIP | BLOCKED | N/A |
| --- | ---: | ---: | ---: | ---: | ---: |
| Formatting / static checks | $(count_status PASS "$asset" "$gofmt_result") | $(count_status FAIL "$asset" "$gofmt_result") | $(count_status SKIP "$asset" "$gofmt_result") | $(count_status BLOCKED "$asset" "$gofmt_result") | 0 |
| Unit tests | $(count_status PASS "$tests") | $(count_status FAIL "$tests") | $(count_status SKIP "$tests") | $(count_status BLOCKED "$tests") | 0 |
| Integration tests | $(count_status PASS "$visual") | $(count_status FAIL "$visual") | $(count_status SKIP "$visual") | $(count_status BLOCKED "$visual") | 0 |
| Contract validation | 0 | 0 | 0 | 0 | 1 |
| Build / packaging | $(count_status PASS "$build") | $(count_status FAIL "$build") | $(count_status SKIP "$build") | $(count_status BLOCKED "$build") | 0 |
| Coverage / metrics | 0 | 0 | 0 | 0 | 1 |
| Release / readiness / load / lab | 0 | 0 | 0 | 0 | 1 |

## Detailed Results

| ID | Check | Result | Evidence | Duration | Notes |
| --- | --- | --- | --- | --- | --- |
| CI-001 | Brand film asset exists and is larger than 1 MB | ${asset} | static/assets/realtek-brand-film.mp4 size check | N/A | Prevents accidentally losing the local brand film asset. |
| CI-002 | Go files are formatted | ${gofmt_result} | gofmt -l over tracked Go files | N/A | Fails if gofmt reports files. |
| CI-003 | Go tests pass | ${tests} | go test ./... | N/A | Covers server, content, analytics, leads, manual, and web packages. |
| CI-004 | Server builds | ${build} | go build ./cmd/server | N/A | Confirms the deployable server package compiles. |
| CI-005 | Visual smoke passes | ${visual} | go run ./cmd/visual-smoke | N/A | Checks representative desktop/mobile pages and asset loading. |
| CI-006 | Contract validation | ${contract} | N/A | N/A | No separate contract validator is configured for this frontend profile. |

## Correctness / Behavior Gates

| Behavior group | Required evidence | Representative test or command | Result | Notes |
| --- | --- | --- | --- | --- |
| Public website routing and forms | Go package tests pass | go test ./... | ${tests} | Includes localized routes, contact validation, analytics, admin, and metadata tests. |
| Visual and responsive smoke | Desktop/mobile smoke output | go run ./cmd/visual-smoke | ${visual} | Ensures home/manual/feature pages render without horizontal overflow in representative viewports. |
| Static asset integrity | Brand film asset check | wc -c static/assets/realtek-brand-film.mp4 | ${asset} | Keeps the local MP4 asset present for the brand film section. |

EOF
      write_tail "docs/TEST_REPORT.md" ".artifacts/raw/ci" ".artifacts/report-candidates/docs"
    } > "$output"
    ;;
  cd)
    source_video="$(result_or_pass "${REPORT_SOURCE_VIDEO_RESULT:-}")"
    bundle="$(result_or_pass "${REPORT_BUNDLE_RESULT:-}")"
    deploy="$(result_or_pass "${REPORT_DEPLOY_RESULT:-}")"
    health="$(result_or_pass "${REPORT_HEALTH_RESULT:-}")"
    homepage="$(result_or_pass "${REPORT_HOMEPAGE_RESULT:-}")"
    deployed_video="$(result_or_pass "${REPORT_DEPLOYED_VIDEO_RESULT:-}")"
    stale="$(result_or_pass "${REPORT_STALE_COPY_RESULT:-}")"
    overall="$(overall_result "$source_video" "$bundle" "$deploy" "$health" "$homepage" "$deployed_video" "$stale")"
    REPORT_ARTIFACT_VERSION_NOTE="N/A - this report validates website source and legacy website-test readiness, not a release artifact version or LKE image."
    REPORT_SERVICE_DEPENDENCIES="SQLite runtime for tests; legacy website test host for CD readiness profile when applicable"
    REPORT_COMMANDS=$'test "$(wc -c < static/assets/realtek-brand-film.mp4)" -gt 1000000\nGOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o dist/bin/realtek-connect ./cmd/server\ntar -C dist -czf - bin content templates static data | sudo /usr/local/sbin/deploy-realtek-connect\ncurl -k -fsS --max-time 20 "${PUBLIC_BASE_URL}/healthz"\ncurl -k -fsS --max-time 20 "${PUBLIC_BASE_URL}/"\ncurl -k -fsSI --max-time 20 "${PUBLIC_BASE_URL}/static/assets/realtek-brand-film.mp4"\ngrep -qv "Contact Sales" deployed homepage snapshot'
    {
      write_common_header "Realtek Connect+ Readiness Test Report" "Legacy website-test readiness evidence" "$overall" "Legacy CD validation for native bundle build, website-test deployment, public health check, homepage verification, video asset verification, and stale-copy checks. Official LKE rollout evidence is produced by the workspace deployment flow."
      cat <<EOF
| Category | PASS | FAIL | SKIP | BLOCKED | N/A |
| --- | ---: | ---: | ---: | ---: | ---: |
| Formatting / static checks | $(count_status PASS "$source_video") | $(count_status FAIL "$source_video") | $(count_status SKIP "$source_video") | $(count_status BLOCKED "$source_video") | 0 |
| Unit tests | 0 | 0 | 0 | 0 | 1 |
| Integration tests | 0 | 0 | 0 | 0 | 1 |
| Contract validation | 0 | 0 | 0 | 0 | 1 |
| Build / packaging | $(count_status PASS "$bundle") | $(count_status FAIL "$bundle") | $(count_status SKIP "$bundle") | $(count_status BLOCKED "$bundle") | 0 |
| Coverage / metrics | 0 | 0 | 0 | 0 | 1 |
| Release / readiness / load / lab | $(count_status PASS "$deploy" "$health" "$homepage" "$deployed_video" "$stale") | $(count_status FAIL "$deploy" "$health" "$homepage" "$deployed_video" "$stale") | $(count_status SKIP "$deploy" "$health" "$homepage" "$deployed_video" "$stale") | $(count_status BLOCKED "$deploy" "$health" "$homepage" "$deployed_video" "$stale") | 0 |

## Detailed Results

| ID | Check | Result | Evidence | Duration | Notes |
| --- | --- | --- | --- | --- | --- |
| CD-001 | Source brand film asset exists and is larger than 1 MB | ${source_video} | static/assets/realtek-brand-film.mp4 size check | N/A | Prevents packaging a deployment without the local MP4. |
| CD-002 | Legacy website-test bundle builds | ${bundle} | dist/bin/realtek-connect plus content/templates/static/data bundle | N/A | Produces the Linux amd64 native bundle for website-test validation. |
| CD-003 | Legacy website-test deploy succeeds | ${deploy} | /usr/local/sbin/deploy-realtek-connect | N/A | Deploys only to the configured legacy website-test host; this is not the official LKE rollout path. |
| CD-004 | Public health check returns ok | ${health} | ${PUBLIC_BASE_URL:-https://webtest.mgmeet.io}/healthz | N/A | Verifies the deployed service is responding. |
| CD-005 | Public homepage contains expected product copy | ${homepage} | ${PUBLIC_BASE_URL:-https://webtest.mgmeet.io}/ | N/A | Confirms deployed homepage contains Realtek Connect and Contact Us. |
| CD-006 | Public video asset is served as MP4 and larger than 1 MB | ${deployed_video} | ${PUBLIC_BASE_URL:-https://webtest.mgmeet.io}/static/assets/realtek-brand-film.mp4 | N/A | Confirms deployed local video asset is reachable. |
| CD-007 | Stale public copy is absent | ${stale} | deployed homepage snapshot | N/A | Guards against stale Contact Sales copy. |

## Correctness / Behavior Gates

| Behavior group | Required evidence | Representative test or command | Result | Notes |
| --- | --- | --- | --- | --- |
| Native bundle integrity | Linux amd64 binary and required runtime directories exist | Build legacy website-test bundle step | ${bundle} | Verifies server, content, templates, static assets, and writable data directory are packaged for legacy validation. |
| Public website-test readiness | Health and homepage checks pass | curl healthz and homepage | $(overall_result "$health" "$homepage") | Confirms the legacy website-test URL serves the expected site. |
| Local video asset readiness | Source and deployed video checks pass | source size check and deployed HEAD request | $(overall_result "$source_video" "$deployed_video") | Ensures the brand film remains first-party local media. |
| Stale-copy prevention | Homepage no longer contains legacy CTA text | grep stale-copy check | ${stale} | Keeps Contact Us wording deployed. |

EOF
      write_tail "docs/READINESS_TEST_REPORT.md" ".artifacts/raw/cd" ".artifacts/report-candidates/docs"
    } > "$output"
    ;;
  *)
    echo "unknown profile: $profile" >&2
    exit 2
    ;;
esac
